version: '3.9'
services:
  chanbot_db:
    container_name: 'chanbot_db'
    image: mongo:latest
    ports:
      - "49153:27017"
    environment:
      MONGO_INITDB_ROOT_DATABASE: root-db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro



